name: "Boiler Controller Config"
description: "Configuration panel for ESPlan Boiler Controller"
version: "0.1.0"
slug: "boiler_config"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "Web UI"
options:
  mqtt_host: "192.168.20.27"
  mqtt_port: 1883
  mqtt_user: "gasburner"
  mqtt_password: "2qBWx35yfqgJrDYF"
  mqtt_topic_prefix: "boiler"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: password
  mqtt_topic_prefix: str
ingress: true
ingress_port: 8099
panel_icon: "mdi:fire"
panel_title: "Boiler Config"
host_network: true
